from __future__ import annotations

from typing import Hashable, Protocol, runtime_checkable

from .models import GameResult, Move, PlayedMove, TacticalMoves


@runtime_checkable
class RulesEngine(Protocol):
    def clone_state(self, state: object) -> object: ...
    def is_legal_move(self, state: object, move: Move, player: int) -> bool: ...
    def apply_move(self, state: object, move: Move, player: int) -> object: ...
    def undo_move(self, state: object, undo_token: object) -> None: ...
    def get_result(self, state: object) -> GameResult: ...
    def get_current_player(self, state: object) -> int: ...
    def get_capture_count(self, state: object, player: int) -> int: ...
    def get_board_cell(self, state: object, row: int, col: int) -> int: ...
    def get_state_hash_data(self, state: object) -> Hashable: ...
    def get_tactical_moves(self, state: object, player: int) -> TacticalMoves: ...
    def get_recent_moves(self, state: object, limit: int) -> tuple[PlayedMove, ...]: ...
